export type SurveyFormData = {
  orderDate: string
  deliveredBy: string
  designImage: string
  designImageQty: string
  designThumb1: string
  designThumb1Qty: string
  designThumb2: string
  designThumb2Qty: string
  designThumb3: string
  designThumb3Qty: string
  jobNo: string
  orderName: string
  ownerName: string
  nic: string
  address: string
  fabric: string
  fabricCustom: string
  quantity: string
  quantityNormal: string
  quantityLeft: string
  quantityRight: string
  sizeHeight: string
  sizeWidth: string
  method: string
  colors: string
  xs: string
  s: string
  m: string
  l: string
  xl: string
  xxl: string
  male: boolean
  female: boolean
  adult: boolean
  children: boolean
  printDescription: string
  printType: string
  embroiderNotes: string
  sublimationNotes: string
  screenPrintNotes: string
  stickerNotes: string
  designDetail: string
  ddMaharagama: boolean
  ddSublimation: boolean
  ddScreenPrint: boolean
  ddSticker: boolean
  ddSubOption: boolean
  ddScreenOption: boolean
  ddStickerOption: boolean
  sewYes: boolean
  sewNo: boolean
  sewCornerTop: boolean
  sewCornerLeft: boolean
  sewCornerRight: boolean
  sewCornerBottom: boolean
  sewCornerTopText: string
  sewCornerLeftText: string
  sewCornerRightText: string
  sewCornerBottomText: string
  paymentStage: string
  paymentNotPaid: boolean
  paymentFull: boolean
  paymentAdvance: boolean
  paymentDeliver: boolean
  deliveryNotes: string
  notes: string
}

export type Submission = {
  id: string
  data: SurveyFormData
  createdAt: string
  financialYear: string
}

export const EMPTY_SURVEY: SurveyFormData = {
  orderDate: '',
  deliveredBy: '',
  designImage: '',
  designImageQty: '',
  designThumb1: '',
  designThumb1Qty: '',
  designThumb2: '',
  designThumb2Qty: '',
  designThumb3: '',
  designThumb3Qty: '',
  jobNo: '',
  orderName: '',
  ownerName: '',
  nic: '',
  address: '',
  fabric: '',
  fabricCustom: '',
  quantity: '',
  quantityNormal: '',
  quantityLeft: '',
  quantityRight: '',
  sizeHeight: '',
  sizeWidth: '',
  method: '',
  colors: '',
  xs: '',
  s: '',
  m: '',
  l: '',
  xl: '',
  xxl: '',
  male: false,
  female: false,
  adult: false,
  children: false,
  printDescription: '',
  printType: '',
  embroiderNotes: '',
  sublimationNotes: '',
  screenPrintNotes: '',
  stickerNotes: '',
  designDetail: '',
  ddMaharagama: false,
  ddSublimation: false,
  ddScreenPrint: false,
  ddSticker: false,
  ddSubOption: false,
  ddScreenOption: false,
  ddStickerOption: false,
  sewYes: false,
  sewNo: false,
  sewCornerTop: false,
  sewCornerLeft: false,
  sewCornerRight: false,
  sewCornerBottom: false,
  sewCornerTopText: '',
  sewCornerLeftText: '',
  sewCornerRightText: '',
  sewCornerBottomText: '',
  paymentStage: '',
  paymentNotPaid: false,
  paymentFull: false,
  paymentAdvance: false,
  paymentDeliver: false,
  deliveryNotes: '',
  notes: '',
}

